spring:
  application:
    name: AccessKey
    #datasourse config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
    #redis config
  redis: # 连接redis服务器
    host: 127.0.0.1
    username:
    password:
    port: 6379

  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 你的邮箱地址
    username: 2521415655@qq.com
    # 授权码
    password: nmhxgknudfqteabd           #授权码，改成你的授权码
    # 编码格式
    default-encoding: utf-8
    # 协议
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

    # 服务端口
server:
  address: localhost
  port: 8080

#短信配置
aliyun:
  sms:
    access-key-id: LTAI5tRDqQQJMXhAKHTV7CAt
    access-key-secret: PiTgbtXYw5ERV9kBlynzuJzZYPy7rV
    sign-name: AccessKey
    template-code: SMS_463760911


# mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.siyi.accesskey.model.domain
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#    lazy-loading-enabled: true # Uncomment if you want to enable lazy loading
#    cache-enabled: true # Uncomment if you want to enable second-level cache
#    local-cache-scope: statement # Uncomment to disable first-level cache

# log
logging:
  level:
    com.siyi.accesskey: debug



