# ???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

# MyBatis ??
mybatis:
  # mapper ???????
  mapperLocations: classpath:mapper/*.xml
  # ????????????
  type-aliases-package: com.kfm.bootmybatis.model
  configuration:
    # ??????
    map-underscore-to-camel-case: true